### ISSUE TITLE
Is it possible to get a new release with last couple of PRs included?

### ISSUE THREAD

**Issue by cars** [vmware/vra-sdk-go#16]
@dmettem @markpeek  Is it possible to get an updated release created with the last couple of PRs included? I've got a pending PR on the terraform provider that needs to content stuff, and I've got some network ip range work in progress I'd like to submit soon as well.

**Comment by dmettem** [comment]
@cars I've created a new release v0.2.7 with last few commits.
I'm closing the issue now. Thanks!
