### ISSUE TITLE
New release needs to have `make swagger` run to pick up recent changes. 

### ISSUE THREAD

**Issue by cars** [vmware/vra-sdk-go#17]
@dmettem   Sorry I wan't clear re #16.  The last change I submitted was updating the return codes via the  _hack/fix_vra_swagger_ script.  So you'll need to run ```make swagger``` to put the change in and rebuild the models/client and then add a new release...

**Comment by dmettem** [comment]
Addressing in #18.

**Comment by dmettem** [comment]
Addressed in #18.
