### ISSUE TITLE
Add on boarding API

### ISSUE THREAD

**Issue by vrabbi** [vmware/vra-sdk-go#24]
The on boarding API is not available in the go sdk.
Is there a reason the full vra API is not in the sdk and only select services?

**Comment by vrabbi** [comment]
Any plans to add this?

**Comment by frodenas** [comment]
Relocation (Onboarding) APIs have been added in #45 and are available in release [v0.5.0](https://github.com/vmware/vra-sdk-go/releases/tag/v0.5.0).
